tests: fix bug-1319374.c compile warnings.
I was looking at a downstream failure of bug-1319374-THIS-crash.t when I
saw the compiler was throwing a warning while running the test:

tests/bugs/gfapi/bug-1319374.c:17:61: warning: implicit declaration of function ‘strerror’; did you mean ‘perror’? [-Wimplicit-function-declaration]
         fprintf(stderr, "\nglfs_new: returned NULL (%s)\n", strerror(errno));
                                                             ^~~~~~~~
                                                             perror

So I compiled the .c with -Wall and saw a lot many more warnings, all
due of a missing header. This patch fixes it.

fixes: bz#1708163
Change-Id: I8b6dd8e1404178a3d99b2d92d01f4575f5203e58
Signed-off-by: Ravishankar N <ravishankar@redhat.com>