tests: Remove explicit mention of include location
This hopefully fixes the spurious failures with

 error: glusterfs/api/glfs.h No such file or directory

build.gluster.org/job/rackspace-regression-2GB-triggered/22897/consoleFull

BUG: 1365489
Change-Id: Ic3660de810c0daee7284373bbfaed172aba86d69
Signed-off-by: Poornima G <pgurusid@redhat.com>
Reviewed-on: http://review.gluster.org/15194
NetBSD-regression: NetBSD Build System <jenkins@build.gluster.org>
CentOS-regression: Gluster Build System <jenkins@build.gluster.org>
Reviewed-by: Raghavendra Talur <rtalur@redhat.com>
Smoke: Gluster Build System <jenkins@build.gluster.org>