syncdaemon: use "ping" message instead of "__version__" to wait for remote to come up
Signed-off-by: Csaba Henk <csaba@gluster.com>
Signed-off-by: Anand V. Avati <avati@dev.gluster.com>

BUG: 2424 (Starting gsyncd with --debug : AttributeError: type object 'FILEServer' has no attribute '__version__')
URL: http://bugs.gluster.com/cgi-bin/bugzilla3/show_bug.cgi?id=2424