eventsapi/packaging: Fix conflict during rpm install
RPM installation fails with following error

  Error: Transaction check error:
    file /etc/glusterfs/eventsconfig.json conflicts between attempted
    installs of glusterfs-events-3.10dev-0.51.gitc9271ff.fc24.x86_64
    and glusterfs-server-3.10dev-0.51.gitc9271ff.fc24.x86_64

Changed attributes of eventsconfig.json file as same as other
config files and excluded this file in server rpm.

BUG: 1375532
Change-Id: I3708c8fc58448cd5a6ebe611250f10e0658bdd58
Signed-off-by: Aravinda VK <avishwan@redhat.com>
Reviewed-on: http://review.gluster.org/15486
Smoke: Gluster Build System <jenkins@build.gluster.org>
CentOS-regression: Gluster Build System <jenkins@build.gluster.org>
Reviewed-by: Niels de Vos <ndevos@redhat.com>
NetBSD-regression: NetBSD Build System <jenkins@build.gluster.org>